### ISSUE TITLE
Sliders play tail hitsounds on overly early release

### ISSUE THREAD

**Issue by ghost** [LumpBloom7/sentakki#10]
title is a bad explanation, sorry. Releasing a slider overly early plays the tail hitsound, even though it should technically count as a miss and so not play a hitsound. It leaves the end hitsound misplaced and confusing.

**Comment by LumpBloom7** [comment]
Not sure if I would consider this a problem. All the notes in all the rulesets I know of operate like this. (including mania's hold notes)
I would consider it even more confusing if the hitsounds were following the note times instead of user triggered input.

**Comment by LumpBloom7** [comment]
Misunderstood the problem. Fixed in ca679700183067af185baaaca291d57337114117
