### ISSUE TITLE
Various issues during gameplay

### ISSUE THREAD

**Issue by Neko-Tsuki** [LumpBloom7/sentakki#137]
In the game, the touch screen no longer seems to be above the specified decision area. When an object is tapped, it is not possible to identify and accurately determine whether or not the object was hit. The slider's sliding judgement is very strange and you can't get it right every time! I hope it can be improved.

**Comment by LumpBloom7** [comment]
Could you please provide information about your system? (system specs, sentakki/lazer version) 

Are you using touch screen?

A video showing the problem would also be very helpful if you could provide that.

**Comment by LumpBloom7** [comment]
Also, I'm a bit lost on what issue you're describing.

> In the game, the touch screen no longer seems to be above the specified decision area. 

This tells me that hit areas are not working, or in a completely different position. Definitely not something that I would expect, so I need some clarification on that.

> When an object is tapped, it is not possible to identify and accurately determine whether or not the object was hit

So you can't determine whether you've hit something or not, sounds like the feedback on hit is not clear enough. I'll work on improving that in the future.

> The slider's sliding judgement is very strange and you can't get it right every time! I hope it can be improved.

This sounds like a judgement window problem. The leniency is quite large, so it shouldn't really be a problem (700ms). I'm gonna need more information or something that shows me what you meant by "weirdness".

**Comment by LumpBloom7** [comment]
A period of time has passed without any response from OP.

Will reopen if OP decides to respond.
