### ISSUE TITLE
Crash when using experimental touch notes

### ISSUE THREAD

**Issue by TheShadowEevee** [LumpBloom7/sentakki#150]
While playing the sentakki gamemode with the experimental mod and touch notes enabled, anytime that the star-like object appears it begins to grow before osu!lazer quickly freezes and then crashes. 

This first happened on an unreleased map that I was testing, but I was able to replicate is with other maps, for example this map from the internet beatmap pack Vol. 1 (https://osu.ppy.sh/beatmapsets/332436#osu/755258) Crashes at around 13% on the "Baraatje123's Juicer" difficulty. 

I've uploaded the runtime.log, which appears to be the only important one for this. It specifies "System.NullReferenceException: Object reference not set to an instance of an object." as the error. I am running the latest version of osu!lazer, 2020.1204.0.0, and the latest version of the sentakki ruleset.

**Comment by LumpBloom7** [comment]
Are you on the latest version of osu!lazer? (the one from today)

**Comment by TheShadowEevee** [comment]
Yeah, Updated this morning, v.2020.1204.0.0

**Comment by TheShadowEevee** [comment]
I said I had uploaded the runtime.log, but than apparently forgot to do that. I'm uploading it now if that will help.
[runtime.log](https://github.com/LumpBloom7/sentakki/files/5643845/runtime.log)

**Comment by LumpBloom7** [comment]
I expected the next lazer update to cause problems, prolly should've waited another few hours before releasing that version of sentakki.

I'll be making another build of sentakki later, for now I believe you should be able to go to the previous version of sentakki.

**Comment by TheShadowEevee** [comment]
Yeah, it looks like version 2020.1121.0 of sentakki does work normally with the latest version. The newest sentakki version and lazer v.2020.1203.0 work fine as well for me, so it's definitely an issue with today's lazer update and sentakki update.

**Comment by LumpBloom7** [comment]
@TheShadowEevee I've made a fresh release, which contains several fixes and performance improvements from 2020.1121.0.

I'll be closing this issue because of that.
