### ISSUE TITLE
Invalid note type during convert?

### ISSUE THREAD

**Issue by ReiFan49** [LumpBloom7/sentakki#186]
Hello, I would like to ask about several matters that bugs me being driven away from the actual "sentaku".

## 1-tile away slides
![](https://cdn.discordapp.com/attachments/785799354668810250/814862680896438272/unknown.png)

I know this is a convert, what I want to ask is "Isn't a very short slide notes are rather impossible in general?". iirc the original one had around 2~8 ticks.

## Break Slide and Break Hold
Is this specific for `sentakki` itself?

## Slide "animation" delay
As what I know that post-tap and the slide animation starts 1 beat interval, I'll assume the interval difference in here is not by bpm?

Also the plan of Slide note will be always attached to Star-skinned Tap as one entity or you could allow the possibility of being UTAGE memes?

I think thats the thing I would like to ask, thanks!

**Comment by LumpBloom7** [comment]
1 tile away slides: I remember seeing something of the sort before in the official game, however I do agree that it is quite unfun seeing as half of the time the end node is immediately triggered.

Break Slide and Break Hold: Slides don't exactly have a break modifier, it is only the tap portion that does, but the color is transferred to the body anyways. Break holds are indeed a sentakki specific addition.

Slide "animation" delay: They are affected by bpm as set by the mapper. Looking at the code more closely, there may be a slight measuring error causing it to be measured in half-beats. So the default delay in converted maps is half a beat, with it not being present if the slide is wayy too short (hardly happens)

**Comment by ReiFan49** [comment]
> 1 tile away slides: I remember seeing something of the sort before in the official game, however I do agree that it is quite unfun seeing as half of the time the end node is immediately triggered.

Hmmm, is this something like Believe the Rainbow? I tried to look on it and it does have at least 2-tiles to operate the stars. If it's utage hmmmmm... should be a different matter of course.

> Break Slide and Break Hold: Slides don't exactly have a break modifier, it is only the tap portion that does, but the color is transferred to the body anyways. Break holds are indeed a sentakki specific addition.

I see. I wonder how confusing the Both Break Slide when it happen to exist (since break color takes precedence over note skin, but don't have precedence over the 

> Slide "animation" delay: They are affected by bpm as set by the mapper. Looking at the code more closely, there may be a slight measuring error causing it to be measured in half-beats. So the default delay in converted maps is half a beat, with it not being present if the slide is wayy too short (hardly happens)

I guess this is rather unintended feature right?

**Comment by LumpBloom7** [comment]
> I see. I wonder how confusing the Both Break Slide when it happen to exist

Break color currently have top priority over Twins

> I guess this is rather unintended feature right?

I think there was a reason for this at the time, maybe because the delay was too long to feel natural

Feel free to visit the discord server for easier discussion on this matter.

**Comment by ReiFan49** [comment]
I see, I guess I can consider this as done for now, may visit later on for possible interests -w-) :thumbsup:

**Comment by LumpBloom7** [comment]
Testing the star delay, it seems that having it default to a full beat causes most stars to not exhibit any delays. And I can recall encountering this issue in the past.

osu std sliders aren't long enough to allow for the star to be delayed a full beat, causing the delay to be cancelled. Forcing the delay would be arguably worse due to the star moving from one end to the other so fast that the star flies over to hishi.

For the sake of being better than the alternative, I'll leave the delay like that.
