### ISSUE TITLE
Slide things from the arcade maimai

### ISSUE THREAD

**Issue by ghost** [LumpBloom7/sentakki#20]
Maybe try to add the slider things across the screen from the real maimai? I feel like that would improve the game, even if it is only on mobile.

EDIT: Maybe add a setting to toggle it.

**Comment by LumpBloom7** [comment]
On the roadmap

**Comment by LumpBloom7** [comment]
It's all part of the plan, can't really imitate the arcade game otherwise..

Regarding the option to toggle it... I'd say no to that. 
It's not that I can't add it.. I just don't see the point. And if people really have an issue with the existence of slide notes, they could just play Tau.
