### ISSUE TITLE
Allow wielding.

### ISSUE THREAD

**Issue by IkaWaAyuMu** [LumpBloom7/sentakki#211]
I want to allow wielding in sentakki because in physical Maimai, there's seperate buttons that allow you to wield (in touch too.). It's so annoying that in spinning thrill note (like on The disapperance of hatsune miku MAS.) you can't wield. and you have to touch rapidly (no one do that in Maimai, I think).

https://user-images.githubusercontent.com/7066150/114339239-ea0f7c00-9b7e-11eb-8830-d8c8e26739d1.mp4

**Comment by LumpBloom7** [comment]
You can wield, but it's disabled by default to lessen the gap for std players that try sentakki.
Within the settings there's an option to change the lane input mode, setting that to "sensor" would enable wielding.
