### ISSUE TITLE
Feature Request/ About Spinner

### ISSUE THREAD

**Issue by MakcSan** [LumpBloom7/sentakki#25]
i thought it would be really. really good for Spinner in this ruleset
When spinner approaches Spin Text Appears above and you need to Spin it It will spin The Circle things entirely 
im really bad at describing things im sorry :c

**Comment by LumpBloom7** [comment]
Do feel free to share your ideas in detail over at the discord server.

**Comment by LumpBloom7** [comment]
Feel free to share your ideas over at the discord server, as it would be a better spot to discuss about a request in detail.

**Comment by MakcSan** [comment]
I Joined 100 discord servers so i cant join :c limit reached

**Comment by LumpBloom7** [comment]
Closing due to lack of useful information to work with.
