### ISSUE TITLE
Touch input doesn't work as expected

### ISSUE THREAD

**Issue by oofyXD** [LumpBloom7/sentakki#257]
I have mouse buttons enabled and still I can't do touchscreen. why?

**Comment by LumpBloom7** [comment]
I assume you are on Windows, currently Windows tries to convert touch input into mouse clicks. The click event only fires when you release your finger. Multitouch also doesn't work as a consequence of the conversion to mouse clicks.

Tracked framework side at https://github.com/ppy/osu-framework/issues/1514 and https://github.com/ppy/osu-framework/issues/4258, but I'll keep this issue to better keep track of things.

PS: I'm not entirely sure, but I believe touch input should work on Linux and MacOS.

**Comment by LumpBloom7** [comment]
Fixed in: https://github.com/ppy/osu-framework/pull/5299
