### ISSUE TITLE
Speed related mods also change note animation times

### ISSUE THREAD

**Issue by LumpBloom7** [LumpBloom7/sentakki#5]
Potential solutions I can think of:
```
1. Adjusting the note duration based on the current playback speed
2. Adjusting note animation to use the approach rate of beatmaps, which avoids the problem of needing to manually set animation speed, but removes a adjustable option that was present in Maimai
3. Ignore the problem and consider it a feature.
```

**Comment by LumpBloom7** [comment]
I noticed that Mania is able to do so without any code to handle it within the drawables, might be handled in `ScrollingPlayfield`..

I could transition to `ScrollingPlayfield`, but given that I will need to implement objects that do not scroll, I'm not sure if it would be worth the effort.

I'm gonna have to study how existing rulesets manage to accommodate speed mods, and make a decision sooner or later.

**Comment by smoogipoo** [comment]
If I understand what you're referring to, mania animation speeds _do_ change with playback speed. I would suggest option (3), however if you really want to "fix" it...

We don't have a simple solution to this, but I can suggest a path: You could try to give your drawables that shouldn't change animation speed a custom clock that has the inverse of the current clock rate applied.

Implementation would be a little tricky - you'd have to take the source time and interpolate yourself (basically implement an `IFrameBasedClock`). Special consideration if you want to consider seeking - you'd may/probably will need to have some sort of threshold beyond which you just reset the animation.

Something like:

```
private IClock parentClock;
private IClock localClock;

[BackgroundDependencyLoader]
private void load()
{
    parentClock = base.Clock;
    lockClock = new MyLocalClock(parentClock);
}

protected override void Update()
{
    base.Update();
    localClock.Rate = 1.0 / parentClock.Rate;
}
```

**Comment by LumpBloom7** [comment]
It turns out I had mania scroll speed too low to make the difference obvious. 

For now I'll ignore it as there are more important things that makes this unplayable.

Keeping this open to acknowledge the problem, and to possibly revisit in the future.
